language: python

# env:
#     global:
#         - COMMIT_AUTHOR_EMAIL: "kevin.walchko@noreply.github.com"

git:
    submodules: false

before_install:
    # - git submodule update --init --recursive
    - rm -fr pelican-plugins
    - git clone --recursive https://github.com/getpelican/pelican-plugins


install:
    - pip install -U pip setuptools wheel
    - pip install -U typogrify Markdown
    - pip install -U pelican

script:
    - make html


deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
    local_dir: www
    project_name: walchko.github.io
    repo: walchko/walchko.github.io
    target_branch: master
    on:
        branch: master
