language: python

# env:
#     global:
#         - COMMIT_AUTHOR_EMAIL: "kevin.walchko@noreply.github.com"

git:
    submodules: false

before_install:
    # - pip install IPython[notebook]
    - git submodule update --init --recursive
    # - git submodule update --init -- pelican-plugins/render_math
    # - git submodule update --init -- pelican-plugins/code_include
    # # - git submodule update --init -- pelican-plugins/sitemap
    # - rm -fr pelican-plugins/liquid_tags


install:
    - pip install -U pip setuptools wheel
    - pip install -U typogrify Markdown
    - pip install -U pelican

script:
    - make html
    # - ls

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
    local_dir: www
    project_name: walchko.github.io
    repo: walchko.github.io
    target_branch: master
    on:
        branch: master
